variables:
  COMPOSE_FILE: "ci/docker-compose.yml"
  PROJECT_REGISTRY: ${PROJECT_REGISTRY}
  NAMESPACE: ${NAMESPACE}
  APP_NAME: "accel-api"
  GIT_USER: "Accel Gitlab Runner"
  GIT_EMAIL: "runner@accel.mitre.org"
  CURRENT_USER: "None"
  GIT_STRATEGY: clone

stages:
  - build
  - test
  - version
  - publish


default:
  tags:
    - accel_docker_builder_runner


.base_job_rules: &base_job_rules
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /^bump:/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_ONLY_CHORES == "true"
      when: never
    - if: $CI_COMMIT_BRANCH


.base_image_job: &base_image_job
  <<: *base_job_rules
  image:
    name: devops.cuic.mitre.org/accel-lab/opendis:ci_${CI_PIPELINE_ID}
    entrypoint: [ "" ]

#
# Build
#
build:
  <<: *base_job_rules
  stage: build
  before_script:
    - echo "$DEV_SERVER_PASSWORD" | docker login $PROJECT_REGISTRY -u $DEV_SERVER_USERNAME --password-stdin
  script:
    # Pull latest changes to debian base image
    - docker pull devops.cuic.mitre.org/cuic-lab/mitre-cuic-debian-bookworm:py3.11
    - docker compose build opendis


#
# Test
#
test:
  <<: *base_image_job
  stage: test
  script:
    - echo "Running tests"
    - pytest --junitxml=./test_results/test_results.xml --cov=opendis --cov-report term --cov-report=xml:./test_results/coverage.xml
  after_script:
    - echo 'All Done!'
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit: test_results/test_results.xml
      coverage_report:
        coverage_format: cobertura
        path: test_results/coverage.xml

#
# Version
#
auto-bump-dev:
  stage: version
  image: 
    name: devops.cuic.mitre.org/accel-lab/opendis:ci_${CI_PIPELINE_ID}
  script:
    - ./ci/auto-bump.sh
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_ONLY_CHORES == "true"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_MESSAGE =~ /^bump:/
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success



#
# Publish
#
include:
  # Test Publish Poetry Component
  - component:  $CI_SERVER_FQDN/cuic-lab/cuic-devops/cicd-templates/poetry-project-ci/publish-poetry@main
    inputs:
      stage: publish
      runner_tag: accel_docker_builder_runner
      image: devops.cuic.mitre.org/cuic-lab/mitre-cuic-debian-bookworm:py3.11


publish:poetry_build_and_publish:
  # Override the build rules for the include
  rules:
    - if: $CI_COMMIT_TAG  # publish on tag
      when: on_success
    - when: never
