name: opendis

services:
  opendis:
    # By default just runs tests when spun up; see entrypoint
    image: devops.cuic.mitre.org/accel-lab/opendis:${version?:err}
    pull_policy: build
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      secrets:
        - dev_server_username
        - dev_server_password
    container_name: opendis
    volumes:
      - .:/home/cuic-dev/accel-open-dis-python
      - ./opendis:/usr/local/lib/python3.11/site-packages/opendis

secrets:
  dev_server_password:
    environment: DEV_SERVER_PASSWORD
  dev_server_username:
    environment: DEV_SERVER_USERNAME
