'''
/*
 * Copyright (c) 2008-2022, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
 // header autogenerated using string template dis7javalicense.txt
'''


from enum import Enum, EnumMeta
from pprint import pprint, pformat
from collections import OrderedDict, namedtuple
import ctypes

UInt8 = ctypes.c_uint8
UInt16 = ctypes.c_uint16
UInt32 = ctypes.c_uint32

EnumValue = namedtuple('EnumValue', ['value', 'description'])

# autogenerated using string template disenumpart1.txt
#  package edu.nps.moves.dis7.enumerations;

'''
/**
  * This <code>enum</code> type is generated from XML,
  * SisoDate : 
  * UID 59,
  * marshal size 32;
  * ArticulatedPartsTypeClass has 263 enumerations total.
  */
'''

class EnumMeta(EnumMeta):
    def __getitem__(cls, name):
        try:
            return super().__getitem__(name)
        except KeyError as error:
            return cls.UNKNOWN
    
    def __getattr__(cls, name):
        try:
            return super().__getattr__(name)
        except AttributeError as error:
            return cls.UNKNOWN

class ExtensibleEnum(Enum):
    @classmethod
    def add_custom_value(cls, value: int, name: str, desc:str):
        existingItem = [item for item in cls._value2member_map_ if item.value == value]

        enumValue = EnumValue(value, desc)
        obj = object.__new__(cls)
        
        obj._value_ = enumValue
        obj._name_ = name      
        obj._desc = desc
        obj.__objclass__ = cls
        
        if not existingItem:
            cls._member_map_[name] = obj
            cls._value2member_map_[enumValue] = enumValue
            cls._member_names_.append(name)
        else:
            enumIndex = list(OrderedDict(cls.__members__).keys())[value]
            cls._member_map_[enumIndex] = obj

    @property
    def get_description(self):
        return self.value.description

    @classmethod
    def to_string(cls) -> str:
        return pformat(OrderedDict(cls.__members__))

    @classmethod
    def is_valid(cls, kind: Enum) -> bool:
        if kind is cls.UNKNOWN:
            return False
        return kind in iter(cls)

    @staticmethod
    def describe(self):
        return self.name, self.value

    @classmethod
    def value_list(cls):
        return list(map(lambda c: c.value, cls))

    @classmethod
    def _missing_(cls, value):
        return cls.default

    @classmethod
    def get_enum_key(cls, value:int) -> str:
        for unique_key, unique_value in OrderedDict(cls.__members__).items():
            if value == unique_value.value.value:
                return unique_key
        return 'UNKNOWN'

    @classmethod
    def get_enum(cls, value:int) -> Enum:
        key = cls.get_enum_key(value)
        return getattr(cls, key)

    def __int__(self):
        return self.value.value
    def diff(self,other) -> set:
        diffs = set()
        for key, value in self.__dict__.items():
            value2 = other.__dict__[key]
            if (value != value2):
                if type(value) is list:
                    diffs.add((key, str(value)))
                    diffs.add((key, str(value2)))
                elif (type(value).__module__ == "builtins"):
                    diffs.add((key, value))
                    diffs.add((key, value2))
                elif (isinstance(value, Enum)):
                    diffs.add((key, value))
                    diffs.add((key, value2))
                elif (isinstance(value, object)):
                    diffs.update(value.diff(value2))
                else:
                    diffs.add((key, value))
                    diffs.add((key, value2))
        return(diffs)

class ArticulatedPartsTypeClass(ExtensibleEnum, metaclass=EnumMeta):
    UNKNOWN = EnumValue(-1, "UNKNOWN Enum")
    not_specified = EnumValue(0, "Not Specified")
    rudder = EnumValue(1024, "Rudder")
    left_flap = EnumValue(1056, "Left Flap")
    right_flap = EnumValue(1088, "Right Flap")
    left_aileron = EnumValue(1120, "Left Aileron")
    right_aileron = EnumValue(1152, "Right Aileron")
    helicopter_main_rotor = EnumValue(1184, "Helicopter - Main Rotor")
    helicopter_tail_rotor = EnumValue(1216, "Helicopter - Tail Rotor")
    other_aircraft_control_surfaces_defined_as_needed = EnumValue(1248, "Other Aircraft Control Surfaces Defined as Needed")
    propeller_number_1 = EnumValue(1280, "Propeller Number 1")
    propeller_number_2 = EnumValue(1312, "Propeller Number 2")
    propeller_number_3 = EnumValue(1344, "Propeller Number 3")
    propeller_number_4 = EnumValue(1376, "Propeller Number 4")
    left_stabilator_stabilator_number_1 = EnumValue(1408, "Left Stabilator (Stabilator Number 1)")
    right_stabilator_stabilator_number_2 = EnumValue(1440, "Right Stabilator (Stabilator Number 2)")
    left_ruddervator_ruddervator_number_1 = EnumValue(1472, "Left Ruddervator (Ruddervator Number 1)")
    right_ruddervator_ruddervator_number_2 = EnumValue(1504, "Right Ruddervator (Ruddervator Number 2)")
    left_leading_edge_flap_slat = EnumValue(1536, "Left Leading Edge Flap/Slat")
    right_leading_edge_flap_slat = EnumValue(1568, "Right Leading Edge Flap/Slat")
    left_elevator = EnumValue(1600, "Left Elevator")
    right_elevator = EnumValue(1632, "Right Elevator")
    canard_left = EnumValue(1664, "Canard (left)")
    canard_right = EnumValue(1696, "Canard (right)")
    elevon_inner_left = EnumValue(1728, "Elevon Inner (left)")
    elevon_inner_right = EnumValue(1760, "Elevon Inner (right)")
    elevon_middle_left = EnumValue(1792, "Elevon Middle (left)")
    elevon_middle_right = EnumValue(1824, "Elevon Middle (right)")
    elevon_outer_left = EnumValue(1856, "Elevon Outer (left)")
    elevon_outer_right = EnumValue(1888, "Elevon Outer (right)")
    canopy_aircraft = EnumValue(1920, "Canopy (Aircraft)")
    spoiler_left = EnumValue(1952, "Spoiler (left)")
    spoiler_right = EnumValue(1984, "Spoiler (right)")
    periscope = EnumValue(2048, "Periscope")
    generic_antenna = EnumValue(2080, "Generic Antenna")
    snorkel = EnumValue(2112, "Snorkel")
    other_extendible_parts_defined_as_needed = EnumValue(2144, "Other Extendible Parts Defined as Needed")
    dive_plane_sail_left = EnumValue(2176, "Dive Plane (Sail) - Left")
    dive_plane_sail_right = EnumValue(2208, "Dive Plane (Sail) - Right")
    dive_plane_bow_left = EnumValue(2240, "Dive Plane (Bow) - Left")
    dive_plane_bow_right = EnumValue(2272, "Dive Plane (Bow) - Right")
    dive_plane_stern_left = EnumValue(2304, "Dive Plane (Stern) - Left")
    dive_plane_stern_right = EnumValue(2336, "Dive Plane (Stern) - Right")
    left_rudder = EnumValue(2368, "Left Rudder")
    right_rudder = EnumValue(2400, "Right Rudder")
    landing_gear_door_nose = EnumValue(2976, "Landing Gear Door - Nose")
    landing_gear_door_left_main = EnumValue(3008, "Landing Gear Door - Left Main")
    landing_gear_door_right_main = EnumValue(3040, "Landing Gear Door - Right Main")
    landing_gear = EnumValue(3072, "Landing Gear")
    tail_hook = EnumValue(3104, "Tail Hook")
    speed_brake = EnumValue(3136, "Speed Brake")
    left_door_of_primary_weapon_bay = EnumValue(3168, "Left Door of Primary Weapon Bay")
    right_door_of_primary_weapon_bay = EnumValue(3200, "Right Door of Primary Weapon Bay")
    tank_or_apc_hatch = EnumValue(3232, "Tank or APC Hatch")
    wingsweep = EnumValue(3264, "Wingsweep")
    bridge_launcher = EnumValue(3296, "Bridge Launcher")
    bridge_section_1 = EnumValue(3328, "Bridge Section 1")
    bridge_section_2 = EnumValue(3360, "Bridge Section 2")
    bridge_section_3 = EnumValue(3392, "Bridge Section 3")
    primary_blade_1 = EnumValue(3424, "Primary Blade 1")
    primary_blade_2 = EnumValue(3456, "Primary Blade 2")
    primary_boom = EnumValue(3488, "Primary Boom")
    primary_launcher_arm = EnumValue(3520, "Primary Launcher Arm")
    other_fixed_position_parts_defined_as_needed = EnumValue(3552, "Other Fixed Position Parts Defined as Needed")
    landing_gear_nose = EnumValue(3584, "Landing Gear - Nose")
    landing_gear_left_main = EnumValue(3616, "Landing Gear - Left Main")
    landing_gear_right_main = EnumValue(3648, "Landing Gear - Right Main")
    doors_of_left_side_weapon_bay = EnumValue(3680, "Doors of Left Side Weapon Bay")
    doors_of_right_side_weapon_bay = EnumValue(3712, "Doors of Right Side Weapon Bay")
    spot_search_light_1 = EnumValue(3744, "Spot/Search Light #1")
    spot_search_light_2 = EnumValue(3776, "Spot/Search Light #2")
    spot_search_light_3 = EnumValue(3808, "Spot/Search Light #3")
    spot_search_light_4 = EnumValue(3840, "Spot/Search Light #4")
    landing_light = EnumValue(3872, "Landing Light")
    primary_turret_number_1 = EnumValue(4096, "Primary Turret Number 1")
    primary_turret_number_2 = EnumValue(4128, "Primary Turret Number 2")
    primary_turret_number_3 = EnumValue(4160, "Primary Turret Number 3")
    primary_turret_number_4 = EnumValue(4192, "Primary Turret Number 4")
    primary_turret_number_5 = EnumValue(4224, "Primary Turret Number 5")
    primary_turret_number_6 = EnumValue(4256, "Primary Turret Number 6")
    primary_turret_number_7 = EnumValue(4288, "Primary Turret Number 7")
    primary_turret_number_8 = EnumValue(4320, "Primary Turret Number 8")
    primary_turret_number_9 = EnumValue(4352, "Primary Turret Number 9")
    primary_turret_number_10 = EnumValue(4384, "Primary Turret Number 10")
    primary_gun_number_1 = EnumValue(4416, "Primary Gun Number 1")
    primary_gun_number_2 = EnumValue(4448, "Primary Gun Number 2")
    primary_gun_number_3 = EnumValue(4480, "Primary Gun Number 3")
    primary_gun_number_4 = EnumValue(4512, "Primary Gun Number 4")
    primary_gun_number_5 = EnumValue(4544, "Primary Gun Number 5")
    primary_gun_number_6 = EnumValue(4576, "Primary Gun Number 6")
    primary_gun_number_7 = EnumValue(4608, "Primary Gun Number 7")
    primary_gun_number_8 = EnumValue(4640, "Primary Gun Number 8")
    primary_gun_number_9 = EnumValue(4672, "Primary Gun Number 9")
    primary_gun_number_10 = EnumValue(4704, "Primary Gun Number 10")
    primary_launcher_1 = EnumValue(4736, "Primary Launcher 1")
    primary_launcher_2 = EnumValue(4768, "Primary Launcher 2")
    primary_launcher_3 = EnumValue(4800, "Primary Launcher 3")
    primary_launcher_4 = EnumValue(4832, "Primary Launcher 4")
    primary_launcher_5 = EnumValue(4864, "Primary Launcher 5")
    primary_launcher_6 = EnumValue(4896, "Primary Launcher 6")
    primary_launcher_7 = EnumValue(4928, "Primary Launcher 7")
    primary_launcher_8 = EnumValue(4960, "Primary Launcher 8")
    primary_launcher_9 = EnumValue(4992, "Primary Launcher 9")
    primary_launcher_10 = EnumValue(5024, "Primary Launcher 10")
    primary_defense_systems_1 = EnumValue(5056, "Primary Defense Systems 1")
    primary_defense_systems_2 = EnumValue(5088, "Primary Defense Systems 2")
    primary_defense_systems_3 = EnumValue(5120, "Primary Defense Systems 3")
    primary_defense_systems_4 = EnumValue(5152, "Primary Defense Systems 4")
    primary_defense_systems_5 = EnumValue(5184, "Primary Defense Systems 5")
    primary_defense_systems_6 = EnumValue(5216, "Primary Defense Systems 6")
    primary_defense_systems_7 = EnumValue(5248, "Primary Defense Systems 7")
    primary_defense_systems_8 = EnumValue(5280, "Primary Defense Systems 8")
    primary_defense_systems_9 = EnumValue(5312, "Primary Defense Systems 9")
    primary_defense_systems_10 = EnumValue(5344, "Primary Defense Systems 10")
    primary_radar_1 = EnumValue(5376, "Primary Radar 1")
    primary_radar_2 = EnumValue(5408, "Primary Radar 2")
    primary_radar_3 = EnumValue(5440, "Primary Radar 3")
    primary_radar_4 = EnumValue(5472, "Primary Radar 4")
    primary_radar_5 = EnumValue(5504, "Primary Radar 5")
    primary_radar_6 = EnumValue(5536, "Primary Radar 6")
    primary_radar_7 = EnumValue(5568, "Primary Radar 7")
    primary_radar_8 = EnumValue(5600, "Primary Radar 8")
    primary_radar_9 = EnumValue(5632, "Primary Radar 9")
    primary_radar_10 = EnumValue(5664, "Primary Radar 10")
    secondary_turret_number_1 = EnumValue(5696, "Secondary Turret Number 1")
    secondary_turret_number_2 = EnumValue(5728, "Secondary Turret Number 2")
    secondary_turret_number_3 = EnumValue(5760, "Secondary Turret Number 3")
    secondary_turret_number_4 = EnumValue(5792, "Secondary Turret Number 4")
    secondary_turret_number_5 = EnumValue(5824, "Secondary Turret Number 5")
    secondary_turret_number_6 = EnumValue(5856, "Secondary Turret Number 6")
    secondary_turret_number_7 = EnumValue(5888, "Secondary Turret Number 7")
    secondary_turret_number_8 = EnumValue(5920, "Secondary Turret Number 8")
    secondary_turret_number_9 = EnumValue(5952, "Secondary Turret Number 9")
    secondary_turret_number_10 = EnumValue(5984, "Secondary Turret Number 10")
    secondary_gun_number_1 = EnumValue(6016, "Secondary Gun Number 1")
    secondary_gun_number_2 = EnumValue(6048, "Secondary Gun Number 2")
    secondary_gun_number_3 = EnumValue(6080, "Secondary Gun Number 3")
    secondary_gun_number_4 = EnumValue(6112, "Secondary Gun Number 4")
    secondary_gun_number_5 = EnumValue(6144, "Secondary Gun Number 5")
    secondary_gun_number_6 = EnumValue(6176, "Secondary Gun Number 6")
    secondary_gun_number_7 = EnumValue(6208, "Secondary Gun Number 7")
    secondary_gun_number_8 = EnumValue(6240, "Secondary Gun Number 8")
    secondary_gun_number_9 = EnumValue(6272, "Secondary Gun Number 9")
    secondary_gun_number_10 = EnumValue(6304, "Secondary Gun Number 10")
    secondary_launcher_1 = EnumValue(6336, "Secondary Launcher 1")
    secondary_launcher_2 = EnumValue(6368, "Secondary Launcher 2")
    secondary_launcher_3 = EnumValue(6400, "Secondary Launcher 3")
    secondary_launcher_4 = EnumValue(6432, "Secondary Launcher 4")
    secondary_launcher_5 = EnumValue(6464, "Secondary Launcher 5")
    secondary_launcher_6 = EnumValue(6496, "Secondary Launcher 6")
    secondary_launcher_7 = EnumValue(6528, "Secondary Launcher 7")
    secondary_launcher_8 = EnumValue(6560, "Secondary Launcher 8")
    secondary_launcher_9 = EnumValue(6592, "Secondary Launcher 9")
    secondary_launcher_10 = EnumValue(6624, "Secondary Launcher 10")
    secondary_defense_systems_1 = EnumValue(6656, "Secondary Defense Systems 1")
    secondary_defense_systems_2 = EnumValue(6688, "Secondary Defense Systems 2")
    secondary_defense_systems_3 = EnumValue(6720, "Secondary Defense Systems 3")
    secondary_defense_systems_4 = EnumValue(6752, "Secondary Defense Systems 4")
    secondary_defense_systems_5 = EnumValue(6784, "Secondary Defense Systems 5")
    secondary_defense_systems_6 = EnumValue(6816, "Secondary Defense Systems 6")
    secondary_defense_systems_7 = EnumValue(6848, "Secondary Defense Systems 7")
    secondary_defense_systems_8 = EnumValue(6880, "Secondary Defense Systems 8")
    secondary_defense_systems_9 = EnumValue(6912, "Secondary Defense Systems 9")
    secondary_defense_systems_10 = EnumValue(6944, "Secondary Defense Systems 10")
    secondary_radar_1 = EnumValue(6976, "Secondary Radar 1")
    secondary_radar_2 = EnumValue(7008, "Secondary Radar 2")
    secondary_radar_3 = EnumValue(7040, "Secondary Radar 3")
    secondary_radar_4 = EnumValue(7072, "Secondary Radar 4")
    secondary_radar_5 = EnumValue(7104, "Secondary Radar 5")
    secondary_radar_6 = EnumValue(7136, "Secondary Radar 6")
    secondary_radar_7 = EnumValue(7168, "Secondary Radar 7")
    secondary_radar_8 = EnumValue(7200, "Secondary Radar 8")
    secondary_radar_9 = EnumValue(7232, "Secondary Radar 9")
    secondary_radar_10 = EnumValue(7264, "Secondary Radar 10")
    deck_elevator_1 = EnumValue(7296, "Deck Elevator #1")
    deck_elevator_2 = EnumValue(7328, "Deck Elevator #2")
    catapult_1 = EnumValue(7360, "Catapult #1")
    catapult_2 = EnumValue(7392, "Catapult #2")
    jet_blast_deflector_1 = EnumValue(7424, "Jet Blast Deflector #1")
    jet_blast_deflector_2 = EnumValue(7456, "Jet Blast Deflector #2")
    arrestor_wires_1 = EnumValue(7488, "Arrestor Wires #1")
    arrestor_wires_2 = EnumValue(7520, "Arrestor Wires #2")
    arrestor_wires_3 = EnumValue(7552, "Arrestor Wires #3")
    wing_or_rotor_fold = EnumValue(7584, "Wing (or Rotor) Fold")
    fuselage_fold = EnumValue(7616, "Fuselage Fold")
    main_cargo_door = EnumValue(7648, "Main Cargo Door")
    cargo_ramp = EnumValue(7680, "Cargo Ramp")
    air_to_air_refueling_boom = EnumValue(7712, "Air-to-Air Refueling Boom")
    primary_aerial_refueling_receptacle_door = EnumValue(7744, "Primary Aerial Refueling Receptacle Door")
    secondary_aerial_refueling_receptacle_door = EnumValue(7776, "Secondary Aerial Refueling Receptacle Door")
    aerial_refueling_receptacle_latch = EnumValue(7808, "Aerial Refueling Receptacle Latch")
    cargo_door_1 = EnumValue(7840, "Cargo Door #1")
    cargo_door_2 = EnumValue(7872, "Cargo Door #2")
    cargo_door_3 = EnumValue(7904, "Cargo Door #3")
    cargo_door_4 = EnumValue(7936, "Cargo Door #4")
    cargo_door_5 = EnumValue(7968, "Cargo Door #5")
    cargo_door_6 = EnumValue(8000, "Cargo Door #6")
    cargo_door_7 = EnumValue(8032, "Cargo Door #7")
    cargo_door_8 = EnumValue(8064, "Cargo Door #8")
    cargo_door_9 = EnumValue(8096, "Cargo Door #9")
    cargo_door_10 = EnumValue(8128, "Cargo Door #10")
    centre_refuelling_drogue = EnumValue(8160, "Centre Refuelling Drogue")
    port_refuelling_drogue = EnumValue(8192, "Port Refuelling Drogue")
    starboard_refuelling_drogue = EnumValue(8224, "Starboard Refuelling Drogue")
    submarine_engine_exhaust_mast = EnumValue(8256, "Submarine Engine Exhaust Mast")
    submarine_mast_1 = EnumValue(8288, "Submarine Mast #1")
    submarine_mast_2 = EnumValue(8320, "Submarine Mast #2")
    submarine_mast_3 = EnumValue(8352, "Submarine Mast #3")
    submarine_mast_4 = EnumValue(8384, "Submarine Mast #4")
    submarine_mast_5 = EnumValue(8416, "Submarine Mast #5")
    submarine_mast_6 = EnumValue(8448, "Submarine Mast #6")
    submarine_mast_7 = EnumValue(8480, "Submarine Mast #7")
    submarine_mast_8 = EnumValue(8512, "Submarine Mast #8")
    submarine_mast_9 = EnumValue(8544, "Submarine Mast #9")
    submarine_mast_10 = EnumValue(8576, "Submarine Mast #10")
    vectored_thrust_nozzle = EnumValue(8608, "Vectored Thrust Nozzle")
    left_door_of_the_left_weapon_bay = EnumValue(8640, "Left Door of the Left Weapon Bay")
    right_door_of_the_left_weapon_bay = EnumValue(8672, "Right Door of the Left Weapon Bay")
    left_door_of_the_right_weapon_bay = EnumValue(8704, "Left Door of the Right Weapon Bay")
    right_door_of_the_right_weapon_bay = EnumValue(8736, "Right Door of the Right Weapon Bay")
    gun_door = EnumValue(8768, "Gun Door")
    countermeasure_door_left = EnumValue(8800, "Countermeasure Door Left")
    countermeasure_door_right = EnumValue(8832, "Countermeasure Door Right")
    hook_door_forward = EnumValue(8864, "Hook Door Forward")
    hook_door_aft = EnumValue(8896, "Hook Door Aft")
    lift_fan_upper_door = EnumValue(8928, "Lift Fan Upper Door")
    lift_fan_lower_door_left = EnumValue(8960, "Lift Fan Lower Door Left")
    lift_fan_lower_door_right = EnumValue(8992, "Lift Fan Lower Door Right")
    refuel_probe_door = EnumValue(9024, "Refuel Probe Door")
    left_engine_nacelle = EnumValue(9056, "Left Engine Nacelle")
    right_engine_nacelle = EnumValue(9088, "Right Engine Nacelle")
    _1st_left_wheel = EnumValue(9120, "1st Left Wheel")
    _1st_right_wheel = EnumValue(9152, "1st Right Wheel")
    _2nd_left_wheel = EnumValue(9184, "2nd Left Wheel")
    _2nd_right_wheel = EnumValue(9216, "2nd Right Wheel")
    _3rd_left_wheel = EnumValue(9248, "3rd Left Wheel")
    _3rd_right_wheel = EnumValue(9280, "3rd Right Wheel")
    _4th_left_wheel = EnumValue(9312, "4th Left Wheel")
    _4th_right_wheel = EnumValue(9344, "4th Right Wheel")
    _5th_left_wheel = EnumValue(9376, "5th Left Wheel")
    _5th_right_wheel = EnumValue(9408, "5th Right Wheel")
    _6th_left_wheel = EnumValue(9440, "6th Left Wheel")
    _6th_right_wheel = EnumValue(9472, "6th Right Wheel")
    _7th_left_wheel = EnumValue(9504, "7th Left Wheel")
    _7th_right_wheel = EnumValue(9536, "7th Right Wheel")
    _8th_left_wheel = EnumValue(9568, "8th Left Wheel")
    _8th_right_wheel = EnumValue(9600, "8th Right Wheel")
    _9th_left_wheel = EnumValue(9632, "9th Left Wheel")
    _9th_right_wheel = EnumValue(9664, "9th Right Wheel")
    _10th_left_wheel = EnumValue(9696, "10th Left Wheel")
    _10th_right_wheel = EnumValue(9728, "10th Right Wheel")
    refueling_probe = EnumValue(9760, "Refueling Probe")
    steering_wheel = EnumValue(9792, "Steering Wheel")
    crane_body = EnumValue(9824, "Crane Body")
    crane_arm_1 = EnumValue(9856, "Crane Arm 1")
    crane_arm_2 = EnumValue(9888, "Crane Arm 2")
    crane_arm_3 = EnumValue(9920, "Crane Arm 3")
    crane_boom = EnumValue(9952, "Crane Boom")
    crane_hook = EnumValue(9984, "Crane Hook")
    trailer = EnumValue(10016, "Trailer")
    roller_left = EnumValue(10048, "Roller Left")
    roller_right = EnumValue(10080, "Roller Right")
    primary_gun_recoil = EnumValue(10112, "Primary Gun Recoil")
    secondary_gun_recoil = EnumValue(10144, "Secondary Gun Recoil")
    default = not_specified

    def get_marshaled_size(self):
        return 32
