'''
/*
 * Copyright (c) 2008-2022, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
 // header autogenerated using string template dis7javalicense.txt
'''


from enum import Enum, EnumMeta
from pprint import pprint, pformat
from collections import OrderedDict, namedtuple
import ctypes

UInt8 = ctypes.c_uint8
UInt16 = ctypes.c_uint16
UInt32 = ctypes.c_uint32

EnumValue = namedtuple('EnumValue', ['value', 'description'])

# autogenerated using string template disenumpart1.txt
#  package edu.nps.moves.dis7.enumerations;

'''
/**
  * This <code>enum</code> type is generated from XML,
  * SisoDate : 
  * UID 78,
  * marshal size 8;
  * ElectromagneticEmissionBeamFunction has 24 enumerations total.
  */
'''

class EnumMeta(EnumMeta):
    def __getitem__(cls, name):
        try:
            return super().__getitem__(name)
        except KeyError as error:
            return cls.UNKNOWN
    
    def __getattr__(cls, name):
        try:
            return super().__getattr__(name)
        except AttributeError as error:
            return cls.UNKNOWN

class ExtensibleEnum(Enum):
    @classmethod
    def add_custom_value(cls, value: int, name: str, desc:str):
        existingItem = [item for item in cls._value2member_map_ if item.value == value]

        enumValue = EnumValue(value, desc)
        obj = object.__new__(cls)
        
        obj._value_ = enumValue
        obj._name_ = name      
        obj._desc = desc
        obj.__objclass__ = cls
        
        if not existingItem:
            cls._member_map_[name] = obj
            cls._value2member_map_[enumValue] = enumValue
            cls._member_names_.append(name)
        else:
            enumIndex = list(OrderedDict(cls.__members__).keys())[value]
            cls._member_map_[enumIndex] = obj

    @property
    def get_description(self):
        return self.value.description

    @classmethod
    def to_string(cls) -> str:
        return pformat(OrderedDict(cls.__members__))

    @classmethod
    def is_valid(cls, kind: Enum) -> bool:
        if kind is cls.UNKNOWN:
            return False
        return kind in iter(cls)

    @staticmethod
    def describe(self):
        return self.name, self.value

    @classmethod
    def value_list(cls):
        return list(map(lambda c: c.value, cls))

    @classmethod
    def _missing_(cls, value):
        return cls.default

    @classmethod
    def get_enum_key(cls, value:int) -> str:
        for unique_key, unique_value in OrderedDict(cls.__members__).items():
            if value == unique_value.value.value:
                return unique_key
        return 'UNKNOWN'

    @classmethod
    def get_enum(cls, value:int) -> Enum:
        key = cls.get_enum_key(value)
        return getattr(cls, key)

    def __int__(self):
        return self.value.value
    def diff(self,other) -> set:
        diffs = set()
        for key, value in self.__dict__.items():
            value2 = other.__dict__[key]
            if (value != value2):
                if type(value) is list:
                    diffs.add((key, str(value)))
                    diffs.add((key, str(value2)))
                elif (type(value).__module__ == "builtins"):
                    diffs.add((key, value))
                    diffs.add((key, value2))
                elif (isinstance(value, Enum)):
                    diffs.add((key, value))
                    diffs.add((key, value2))
                elif (isinstance(value, object)):
                    diffs.update(value.diff(value2))
                else:
                    diffs.add((key, value))
                    diffs.add((key, value2))
        return(diffs)

class ElectromagneticEmissionBeamFunction(ExtensibleEnum, metaclass=EnumMeta):
    UNKNOWN = EnumValue(-1, "UNKNOWN Enum")
    other = EnumValue(0, "Other")
    search = EnumValue(1, "Search")
    height_finding = EnumValue(2, "Height Finding")
    acquisition = EnumValue(3, "Acquisition")
    tracking = EnumValue(4, "Tracking")
    acquisition_and_tracking = EnumValue(5, "Acquisition and tracking")
    command_guidance = EnumValue(6, "Command guidance")
    illumination = EnumValue(7, "Illumination")
    ranging = EnumValue(8, "Ranging")
    missile_beacon = EnumValue(9, "Missile beacon")
    missile_fusing = EnumValue(10, "Missile Fusing")
    active_radar_missile_seeker = EnumValue(11, "Active radar missile seeker")
    jamming = EnumValue(12, "Jamming")
    iff = EnumValue(13, "IFF")
    navigation_weather = EnumValue(14, "Navigation / Weather")
    meteorological = EnumValue(15, "Meteorological")
    data_transmission = EnumValue(16, "Data transmission")
    navigational_directional_beacon = EnumValue(17, "Navigational directional beacon")
    time_shared_search = EnumValue(20, "Time-Shared Search")
    time_shared_acquisition = EnumValue(21, "Time-Shared Acquisition")
    time_shared_track = EnumValue(22, "Time-Shared Track")
    time_shared_command_guidance = EnumValue(23, "Time-Shared Command Guidance")
    time_shared_illumination = EnumValue(24, "Time-Shared Illumination")
    time_shared_jamming = EnumValue(25, "Time-Shared Jamming")
    default = other

    def get_marshaled_size(self):
        return 8
