'''
/*
 * Copyright (c) 2008-2022, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
 // header autogenerated using string template dis7javalicense.txt
'''


from enum import Enum, EnumMeta
from pprint import pprint, pformat
from collections import OrderedDict, namedtuple
import ctypes

UInt8 = ctypes.c_uint8
UInt16 = ctypes.c_uint16
UInt32 = ctypes.c_uint32

EnumValue = namedtuple('EnumValue', ['value', 'description'])

# autogenerated using string template disenumpart1.txt
#  package edu.nps.moves.dis7.enumerations;

'''
/**
  * This <code>enum</code> type is generated from XML,
  * SisoDate : 
  * UID 212,
  * marshal size 16;
  * IsPartOfStationName has 23 enumerations total.
  */
'''

class EnumMeta(EnumMeta):
    def __getitem__(cls, name):
        try:
            return super().__getitem__(name)
        except KeyError as error:
            return cls.UNKNOWN
    
    def __getattr__(cls, name):
        try:
            return super().__getattr__(name)
        except AttributeError as error:
            return cls.UNKNOWN

class ExtensibleEnum(Enum):
    @classmethod
    def add_custom_value(cls, value: int, name: str, desc:str):
        existingItem = [item for item in cls._value2member_map_ if item.value == value]

        enumValue = EnumValue(value, desc)
        obj = object.__new__(cls)
        
        obj._value_ = enumValue
        obj._name_ = name      
        obj._desc = desc
        obj.__objclass__ = cls
        
        if not existingItem:
            cls._member_map_[name] = obj
            cls._value2member_map_[enumValue] = enumValue
            cls._member_names_.append(name)
        else:
            enumIndex = list(OrderedDict(cls.__members__).keys())[value]
            cls._member_map_[enumIndex] = obj

    @property
    def get_description(self):
        return self.value.description

    @classmethod
    def to_string(cls) -> str:
        return pformat(OrderedDict(cls.__members__))

    @classmethod
    def is_valid(cls, kind: Enum) -> bool:
        if kind is cls.UNKNOWN:
            return False
        return kind in iter(cls)

    @staticmethod
    def describe(self):
        return self.name, self.value

    @classmethod
    def value_list(cls):
        return list(map(lambda c: c.value, cls))

    @classmethod
    def _missing_(cls, value):
        return cls.default

    @classmethod
    def get_enum_key(cls, value:int) -> str:
        for unique_key, unique_value in OrderedDict(cls.__members__).items():
            if value == unique_value.value.value:
                return unique_key
        return 'UNKNOWN'

    @classmethod
    def get_enum(cls, value:int) -> Enum:
        key = cls.get_enum_key(value)
        return getattr(cls, key)

    def __int__(self):
        return self.value.value
    def diff(self,other) -> set:
        diffs = set()
        for key, value in self.__dict__.items():
            value2 = other.__dict__[key]
            if (value != value2):
                if type(value) is list:
                    diffs.add((key, str(value)))
                    diffs.add((key, str(value2)))
                elif (type(value).__module__ == "builtins"):
                    diffs.add((key, value))
                    diffs.add((key, value2))
                elif (isinstance(value, Enum)):
                    diffs.add((key, value))
                    diffs.add((key, value2))
                elif (isinstance(value, object)):
                    diffs.update(value.diff(value2))
                else:
                    diffs.add((key, value))
                    diffs.add((key, value2))
        return(diffs)

class IsPartOfStationName(ExtensibleEnum, metaclass=EnumMeta):
    UNKNOWN = EnumValue(-1, "UNKNOWN Enum")
    other = EnumValue(0, "Other")
    aircraft_wingstation = EnumValue(1, "Aircraft Wingstation")
    ships_forward_gunmount_starboard = EnumValue(2, "Ship's Forward Gunmount (Starboard)")
    ships_forward_gunmount_port = EnumValue(3, "Ship's Forward Gunmount (Port)")
    ships_forward_gunmount_centerline = EnumValue(4, "Ship's Forward Gunmount (Centerline)")
    ships_aft_gunmount_starboard = EnumValue(5, "Ship's Aft Gunmount (Starboard)")
    ships_aft_gunmount_port = EnumValue(6, "Ship's Aft Gunmount (Port)")
    ships_aft_gunmount_centerline = EnumValue(7, "Ship's Aft Gunmount (Centerline)")
    forward_torpedo_tube = EnumValue(8, "Forward Torpedo Tube")
    aft_torpedo_tube = EnumValue(9, "Aft Torpedo Tube")
    bomb_bay = EnumValue(10, "Bomb Bay")
    cargo_bay = EnumValue(11, "Cargo Bay")
    truck_bed = EnumValue(12, "Truck Bed")
    trailer_bed = EnumValue(13, "Trailer Bed")
    well_deck = EnumValue(14, "Well Deck")
    on_station_range_and_bearing = EnumValue(15, "On Station Range and Bearing")
    on_station_xyz = EnumValue(16, "On Station xyz")
    air_to_air_refueling_boom = EnumValue(17, "Air-to-Air Refueling Boom")
    aerial_refueling_receptacle = EnumValue(18, "Aerial Refueling Receptacle")
    port_side_refueling_drogue = EnumValue(19, "Port Side Refueling Drogue")
    starboard_side_refueling_drogue = EnumValue(20, "Starboard Side Refueling Drogue")
    center_refueling_drogue = EnumValue(21, "Center Refueling Drogue")
    air_refueling_probe = EnumValue(22, "Air Refueling Probe")
    default = other

    def get_marshaled_size(self):
        return 16
