'''
/*
 * Copyright (c) 2008-2022, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
 // header autogenerated using string template dis7javalicense.txt
'''


from enum import Enum, EnumMeta
from pprint import pprint, pformat
from collections import OrderedDict, namedtuple
import ctypes

UInt8 = ctypes.c_uint8
UInt16 = ctypes.c_uint16
UInt32 = ctypes.c_uint32

EnumValue = namedtuple('EnumValue', ['value', 'description'])

# autogenerated using string template disenumpart1.txt
#  package edu.nps.moves.dis7.enumerations;

'''
/**
  * This <code>enum</code> type is generated from XML,
  * SisoDate : 
  * UID 513,
  * marshal size 8;
  * LifeFormHumanSpecificHandGuns has 26 enumerations total.
  */
'''

class EnumMeta(EnumMeta):
    def __getitem__(cls, name):
        try:
            return super().__getitem__(name)
        except KeyError as error:
            return cls.UNKNOWN
    
    def __getattr__(cls, name):
        try:
            return super().__getattr__(name)
        except AttributeError as error:
            return cls.UNKNOWN

class ExtensibleEnum(Enum):
    @classmethod
    def add_custom_value(cls, value: int, name: str, desc:str):
        existingItem = [item for item in cls._value2member_map_ if item.value == value]

        enumValue = EnumValue(value, desc)
        obj = object.__new__(cls)
        
        obj._value_ = enumValue
        obj._name_ = name      
        obj._desc = desc
        obj.__objclass__ = cls
        
        if not existingItem:
            cls._member_map_[name] = obj
            cls._value2member_map_[enumValue] = enumValue
            cls._member_names_.append(name)
        else:
            enumIndex = list(OrderedDict(cls.__members__).keys())[value]
            cls._member_map_[enumIndex] = obj

    @property
    def get_description(self):
        return self.value.description

    @classmethod
    def to_string(cls) -> str:
        return pformat(OrderedDict(cls.__members__))

    @classmethod
    def is_valid(cls, kind: Enum) -> bool:
        if kind is cls.UNKNOWN:
            return False
        return kind in iter(cls)

    @staticmethod
    def describe(self):
        return self.name, self.value

    @classmethod
    def value_list(cls):
        return list(map(lambda c: c.value, cls))

    @classmethod
    def _missing_(cls, value):
        return cls.default

    @classmethod
    def get_enum_key(cls, value:int) -> str:
        for unique_key, unique_value in OrderedDict(cls.__members__).items():
            if value == unique_value.value.value:
                return unique_key
        return 'UNKNOWN'

    @classmethod
    def get_enum(cls, value:int) -> Enum:
        key = cls.get_enum_key(value)
        return getattr(cls, key)

    def __int__(self):
        return self.value.value
    def diff(self,other) -> set:
        diffs = set()
        for key, value in self.__dict__.items():
            value2 = other.__dict__[key]
            if (value != value2):
                if type(value) is list:
                    diffs.add((key, str(value)))
                    diffs.add((key, str(value2)))
                elif (type(value).__module__ == "builtins"):
                    diffs.add((key, value))
                    diffs.add((key, value2))
                elif (isinstance(value, Enum)):
                    diffs.add((key, value))
                    diffs.add((key, value2))
                elif (isinstance(value, object)):
                    diffs.update(value.diff(value2))
                else:
                    diffs.add((key, value))
                    diffs.add((key, value2))
        return(diffs)

class LifeFormHumanSpecificHandGuns(ExtensibleEnum, metaclass=EnumMeta):
    UNKNOWN = EnumValue(-1, "UNKNOWN Enum")
    other = EnumValue(0, "Other")
    _545mm_psm = EnumValue(1, "5.45mm PSM")
    _58mm_norinco_qsz_92 = EnumValue(10, "5.8mm Norinco QSZ-92")
    _9mm_mk3_slp = EnumValue(30, "9mm MK3 SLP")
    _9mm_beretta_92s_92fs_m9 = EnumValue(31, "9mm Beretta 92S/92FS (M9)")
    _9mm_hamp_k_usp = EnumValue(32, "9mm H&amp;K USP")
    _9mm_stechkin_aps = EnumValue(33, "9mm Stechkin APS")
    _9mm_makarov_pm = EnumValue(34, "9mm Makarov PM")
    _9mm_smith_and_wesson_sd_sigma = EnumValue(35, "9mm Smith and Wesson SD (Sigma)")
    _9mm_glock_17 = EnumValue(36, "9mm Glock 17")
    _9mm_sig_sauer_m17 = EnumValue(37, "9mm SIG Sauer M17")
    _9mm_sig_pro = EnumValue(38, "9mm SIG Pro")
    _9mm_smith_and_wesson_sw1911 = EnumValue(39, "9mm Smith and Wesson SW1911")
    _9mm_smith_and_wesson_5900_series = EnumValue(40, "9mm Smith and Wesson 5900-series")
    _45_cal_m1911 = EnumValue(41, ".45 Cal M1911")
    _9mm_cz_75 = EnumValue(42, "9mm CZ 75")
    _9mm_cz_82 = EnumValue(43, "9mm CZ 82")
    _9mm_norinco_qsz_92_cf_98 = EnumValue(44, "9mm Norinco QSZ-92 (CF-98)")
    _9mm_cz_p_10_c = EnumValue(45, "9mm CZ P-10 C")
    _907mm_ruger_gp_100 = EnumValue(50, "9.07mm Ruger GP 100")
    _10mm_glock_20 = EnumValue(60, "10mm Glock 20")
    _9mm_fort_12 = EnumValue(70, "9mm Fort-12")
    _9mm_fort_14tp = EnumValue(71, "9mm Fort-14TP")
    _9mm_fort_17 = EnumValue(72, "9mm Fort-17")
    _9mm_fort_21 = EnumValue(73, "9mm Fort-21")
    _127mm_norinco_np762_px_3 = EnumValue(80, "12.7mm Norinco NP762 (PX-3)")
    default = other

    def get_marshaled_size(self):
        return 8
