'''
/*
 * Copyright (c) 2008-2022, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
 // header autogenerated using string template dis7javalicense.txt
'''


from enum import Enum, EnumMeta
from pprint import pprint, pformat
from collections import OrderedDict, namedtuple
import ctypes

UInt8 = ctypes.c_uint8
UInt16 = ctypes.c_uint16
UInt32 = ctypes.c_uint32

EnumValue = namedtuple('EnumValue', ['value', 'description'])

# autogenerated using string template disenumpart1.txt
#  package edu.nps.moves.dis7.enumerations;

'''
/**
  * This <code>enum</code> type is generated from XML,
  * SisoDate : 
  * UID 511,
  * marshal size 8;
  * LifeFormHumanSpecificShotGuns has 139 enumerations total.
  */
'''

class EnumMeta(EnumMeta):
    def __getitem__(cls, name):
        try:
            return super().__getitem__(name)
        except KeyError as error:
            return cls.UNKNOWN
    
    def __getattr__(cls, name):
        try:
            return super().__getattr__(name)
        except AttributeError as error:
            return cls.UNKNOWN

class ExtensibleEnum(Enum):
    @classmethod
    def add_custom_value(cls, value: int, name: str, desc:str):
        existingItem = [item for item in cls._value2member_map_ if item.value == value]

        enumValue = EnumValue(value, desc)
        obj = object.__new__(cls)
        
        obj._value_ = enumValue
        obj._name_ = name      
        obj._desc = desc
        obj.__objclass__ = cls
        
        if not existingItem:
            cls._member_map_[name] = obj
            cls._value2member_map_[enumValue] = enumValue
            cls._member_names_.append(name)
        else:
            enumIndex = list(OrderedDict(cls.__members__).keys())[value]
            cls._member_map_[enumIndex] = obj

    @property
    def get_description(self):
        return self.value.description

    @classmethod
    def to_string(cls) -> str:
        return pformat(OrderedDict(cls.__members__))

    @classmethod
    def is_valid(cls, kind: Enum) -> bool:
        if kind is cls.UNKNOWN:
            return False
        return kind in iter(cls)

    @staticmethod
    def describe(self):
        return self.name, self.value

    @classmethod
    def value_list(cls):
        return list(map(lambda c: c.value, cls))

    @classmethod
    def _missing_(cls, value):
        return cls.default

    @classmethod
    def get_enum_key(cls, value:int) -> str:
        for unique_key, unique_value in OrderedDict(cls.__members__).items():
            if value == unique_value.value.value:
                return unique_key
        return 'UNKNOWN'

    @classmethod
    def get_enum(cls, value:int) -> Enum:
        key = cls.get_enum_key(value)
        return getattr(cls, key)

    def __int__(self):
        return self.value.value
    def diff(self,other) -> set:
        diffs = set()
        for key, value in self.__dict__.items():
            value2 = other.__dict__[key]
            if (value != value2):
                if type(value) is list:
                    diffs.add((key, str(value)))
                    diffs.add((key, str(value2)))
                elif (type(value).__module__ == "builtins"):
                    diffs.add((key, value))
                    diffs.add((key, value2))
                elif (isinstance(value, Enum)):
                    diffs.add((key, value))
                    diffs.add((key, value2))
                elif (isinstance(value, object)):
                    diffs.update(value.diff(value2))
                else:
                    diffs.add((key, value))
                    diffs.add((key, value2))
        return(diffs)

class LifeFormHumanSpecificShotGuns(ExtensibleEnum, metaclass=EnumMeta):
    UNKNOWN = EnumValue(-1, "UNKNOWN Enum")
    other = EnumValue(0, "Other")
    browning_superposed_o_u = EnumValue(20, "Browning Superposed O/U")
    browning_cynergy = EnumValue(21, "Browning Cynergy")
    browning_auto_5 = EnumValue(22, "Browning Auto-5")
    _185mm_browning_citori_o_u_12_gauge = EnumValue(23, "18.5mm Browning Citori O/U 12 Gauge")
    _168mm_browning_citori_o_u_16_gauge = EnumValue(24, "16.8mm Browning Citori O/U 16 Gauge")
    _156mm_browning_citori_o_u_20_gauge = EnumValue(25, "15.6mm Browning Citori O/U 20 Gauge")
    _14mm_browning_citori_o_u_28_gauge = EnumValue(26, "14mm Browning Citori O/U 28 Gauge")
    _104mm_browning_citori_o_u_410_bore = EnumValue(27, "10.4mm Browning Citori O/U .410 Bore")
    _185mm_browning_double_automatic_12_gauge = EnumValue(28, "18.5mm Browning Double Automatic 12 Gauge")
    _185mm_ithaca_37_12_gauge = EnumValue(29, "18.5mm Ithaca 37 12 Gauge")
    _168mm_ithaca_37_16_gauge = EnumValue(30, "16.8mm Ithaca 37 16 Gauge")
    _156mm_ithaca_37_20_gauge = EnumValue(31, "15.6mm Ithaca 37 20 Gauge")
    _14mm_ithaca_37_28_gauge = EnumValue(32, "14mm Ithaca 37 28 Gauge")
    _197mm_ithaca_mag_10_sa_10_gauge = EnumValue(33, "19.7mm Ithaca Mag-10 SA 10 Gauge")
    _197mm_marlin_model_55_10_gauge = EnumValue(34, "19.7mm Marlin Model 55 10 Gauge")
    _185mm_marlin_model_55_12_gauge = EnumValue(35, "18.5mm Marlin Model 55 12 Gauge")
    _168mm_marlin_model_55_16_gauge = EnumValue(36, "16.8mm Marlin Model 55 16 Gauge")
    _156mm_marlin_model_55_20_gauge = EnumValue(37, "15.6mm Marlin Model 55 20 Gauge")
    _185mm_mossberg_500_12_gauge = EnumValue(38, "18.5mm Mossberg 500 12 Gauge")
    _156mm_mossberg_500_20_gauge = EnumValue(39, "15.6mm Mossberg 500 20 Gauge")
    _104mm_mossberg_500_410_bore = EnumValue(40, "10.4mm Mossberg 500 .410 Bore")
    _185mm_mossberg_590_12_gauge = EnumValue(41, "18.5mm Mossberg 590 12 Gauge")
    _156mm_mossberg_590_20_gauge = EnumValue(42, "15.6mm Mossberg 590 20 Gauge")
    _104mm_mossberg_590_410_bore = EnumValue(43, "10.4mm Mossberg 590 .410 Bore")
    _185mm_mossberg_930_sa_12_gauge = EnumValue(44, "18.5mm Mossberg 930 SA 12 Gauge")
    remington_model_11_sa = EnumValue(45, "Remington Model 11 SA")
    remington_model_10_12_gauge = EnumValue(46, "Remington Model 10 12 Gauge")
    _156mm_remington_model_17_20_gauge = EnumValue(47, "15.6mm Remington Model 17 20 Gauge")
    remington_model_31 = EnumValue(48, "Remington Model 31")
    remington_model_11_48_sa = EnumValue(49, "Remington Model 11-48 SA")
    _185mm_remington_870_12_gauge = EnumValue(50, "18.5mm Remington 870 12 Gauge")
    _168mm_remington_870_16_gauge = EnumValue(51, "16.8mm Remington 870 16 Gauge")
    _156mm_remington_870_20_gauge = EnumValue(52, "15.6mm Remington 870 20 Gauge")
    _14mm_remington_870_28_gauge = EnumValue(53, "14mm Remington 870 28 Gauge")
    _104mm_remington_870_410_bore = EnumValue(54, "10.4mm Remington 870 .410 Bore")
    remington_model_58_sa = EnumValue(55, "Remington Model 58 SA")
    _185mm_remington_878_sa_12_gauge = EnumValue(56, "18.5mm Remington 878 SA 12 Gauge")
    _185mm_remington_model_1100_sa_12_gauge = EnumValue(57, "18.5mm Remington Model 1100 SA 12 Gauge")
    _168mm_remington_model_1100_sa_16_gauge = EnumValue(58, "16.8mm Remington Model 1100 SA 16 Gauge")
    _156mm_remington_model_1100_sa_20_gauge = EnumValue(59, "15.6mm Remington Model 1100 SA 20 Gauge")
    _14mm_remington_model_1100_sa_28_gauge = EnumValue(60, "14mm Remington Model 1100 SA 28 Gauge")
    _104mm_remington_model_1100_sa_410_bore = EnumValue(61, "10.4mm Remington Model 1100 SA .410 Bore")
    _185mm_remington_11_87_sa_12_gauge = EnumValue(62, "18.5mm Remington 11-87 SA 12 Gauge")
    _156mm_remington_11_87_sa_20_gauge = EnumValue(63, "15.6mm Remington 11-87 SA 20 Gauge")
    _197mm_remington_model_sp_10_sa_10_gauge = EnumValue(64, "19.7mm Remington Model SP-10 SA 10 Gauge")
    _185mm_remington_887_12_gauge = EnumValue(65, "18.5mm Remington 887 12 Gauge")
    _185mm_remington_sparta_100_sxs_12_gauge = EnumValue(70, "18.5mm Remington Sparta 100 SxS 12 Gauge")
    _156mm_remington_sparta_100_sxs_20_gauge = EnumValue(71, "15.6mm Remington Sparta 100 SxS 20 Gauge")
    _104mm_remington_sparta_100_sxs_410_bore = EnumValue(72, "10.4mm Remington Sparta 100 SxS .410 Bore")
    _185mm_remington_spartan_310_o_u_12_gauge = EnumValue(73, "18.5mm Remington Spartan 310 O/U 12 Gauge")
    _156mm_remington_spartan_310_o_u_20_gauge = EnumValue(74, "15.6mm Remington Spartan 310 O/U 20 Gauge")
    _14mm_remington_spartan_310_o_u_28_gauge = EnumValue(75, "14mm Remington Spartan 310 O/U 28 Gauge")
    _104mm_remington_spartan_310_o_u_410_bore = EnumValue(76, "10.4mm Remington Spartan 310 O/U .410 Bore")
    _185mm_remington_spartan_453_sa_12_gauge = EnumValue(77, "18.5mm Remington Spartan 453 SA 12 Gauge")
    _185mm_winchester_model_1200_12_gauge = EnumValue(80, "18.5mm Winchester Model 1200 12 Gauge")
    _168mm_winchester_model_1200_16_gauge = EnumValue(81, "16.8mm Winchester Model 1200 16 Gauge")
    _156mm_winchester_model_1200_20_gauge = EnumValue(82, "15.6mm Winchester Model 1200 20 Gauge")
    winchester_model_1887_1901 = EnumValue(83, "Winchester Model 1887/1901")
    winchester_model_1897 = EnumValue(84, "Winchester Model 1897")
    winchester_model_1912 = EnumValue(85, "Winchester Model 1912")
    winchester_model_21_sxs = EnumValue(86, "Winchester Model 21 SxS")
    winchester_model_37_sxs = EnumValue(87, "Winchester Model 37 SxS")
    _185mm_hr_ultraslug_sxs_12_gauge = EnumValue(88, "18.5mm HR Ultraslug SxS 12 Gauge")
    _156mm_hr_ultraslug_sxs_20_gauge = EnumValue(89, "15.6mm HR Ultraslug SxS 20 Gauge")
    _185mm_ciener_ultimate_o_u_12_gauge = EnumValue(90, "18.5mm Ciener Ultimate O/U 12 Gauge")
    _185mm_coach_gun_sxs_double_barrel_12_gauge = EnumValue(91, "18.5mm Coach Gun SxS Double Barrel 12 Gauge")
    _185mm_ruger_gold_label_sxs_12_gauge = EnumValue(92, "18.5mm Ruger Gold Label SxS 12 Gauge")
    _185mm_high_standard_model_10_sa_12_gauge = EnumValue(93, "18.5mm High Standard Model 10 SA 12 Gauge")
    _185mm_kel_tex_ksg_12_gauge = EnumValue(94, "18.5mm Kel-Tex KSG 12 Gauge")
    _185_kac_masterkey_12_gauge = EnumValue(95, "18.5 KAC Masterkey 12 Gauge")
    _185mm_m26_mass_12_gauge = EnumValue(96, "18.5mm M26 M.A.S.S. 12 Gauge")
    _185mm_srm_arms_m1216_sa_12_gauge = EnumValue(97, "18.5mm SRM Arms M1216 SA 12 Gauge")
    _185mm_aa_12_fa_atchisson_assault = EnumValue(98, "18.5mm AA-12 FA Atchisson Assault")
    _185mm_pancor_jackhammer_fa_12_gauge = EnumValue(99, "18.5mm Pancor Jackhammer FA 12 Gauge")
    _185mm_usas_12_fa_12_gauge = EnumValue(110, "18.5mm USAS-12 FA 12 Gauge")
    _185mm_maul_sa_12_gauge = EnumValue(111, "18.5mm MAUL SA 12 Gauge")
    _185mm_fn_slp_sa_12_gauge = EnumValue(112, "18.5mm FN SLP SA 12 Gauge")
    _185mm_fn_tps_12_gauge = EnumValue(113, "18.5mm FN TPS 12 Gauge")
    _185mm_enarm_pentagun_sa_12_gauge = EnumValue(115, "18.5mm ENARM Pentagun SA 12 Gauge")
    stevens_model_520_620 = EnumValue(116, "Stevens Model 520/620")
    stoeger_coach_gun_sxs = EnumValue(117, "Stoeger Coach Gun SxS")
    stoeger_condor_o_u = EnumValue(118, "Stoeger Condor O/U")
    _185mm_armscor_model_30_sa_12_gauge = EnumValue(120, "18.5mm Armscor Model 30 SA 12 Gauge")
    weatherby_sa_08_sa = EnumValue(121, "Weatherby SA-08 SA")
    _185mm_fabarm_sdass_tactical_12_gauge = EnumValue(122, "18.5mm Fabarm SDASS Tactical 12 Gauge")
    _185mm_mag_7_12_gauge = EnumValue(123, "18.5mm MAG-7 12 Gauge")
    _185mm_neostead_12_gauge = EnumValue(124, "18.5mm Neostead 12 Gauge")
    _185mm_armsel_striker_sa_12_gauge = EnumValue(125, "18.5mm Armsel Striker SA 12 Gauge")
    _185mm_parker_hale_rogun_sa_12_gauge = EnumValue(127, "18.5mm Parker Hale Rogun SA 12 Gauge")
    _26mm_rga_86_revolver = EnumValue(130, "26mm RGA-86 Revolver")
    _185mm_sjorgren_sa_12_gauge = EnumValue(131, "18.5mm Sjorgren SA 12 Gauge")
    _185mm_akdal_mka_1919_sa_12_gauge = EnumValue(132, "18.5mm Akdal MKA 1919 SA 12 Gauge")
    _185mm_retay_masai_mara_sa_12_gauge = EnumValue(133, "18.5mm Retay Masai Mara SA 12 Gauge")
    _185mm_safir_t_14_sa_12_gauge = EnumValue(134, "18.5mm Safir T-14 SA 12 Gauge")
    _185mm_benelli_m1_super_90_sa_12_gauge = EnumValue(150, "18.5mm Benelli M1 Super 90 SA 12 Gauge")
    _156mm_benelli_m1_super_90_sa_20_gauge = EnumValue(151, "15.6mm Benelli M1 Super 90 SA 20 Gauge")
    _185mm_benelli_m3_super_90_sa_12_gauge = EnumValue(152, "18.5mm Benelli M3 Super 90 SA 12 Gauge")
    _156mm_benelli_m3_super_90_sa_20_gauge = EnumValue(153, "15.6mm Benelli M3 Super 90 SA 20 Gauge")
    _185mm_benelli_m4_super_90_sa_12_gauge = EnumValue(154, "18.5mm Benelli M4 Super 90 SA 12 Gauge")
    _185mm_benelli_nova_12_gauge = EnumValue(155, "18.5mm Benelli Nova 12 Gauge")
    _156mm_benelli_nove_20_gauge = EnumValue(156, "15.6mm Benelli Nove 20 Gauge")
    _185mm_benelli_raffaello_sa_12_gauge = EnumValue(157, "18.5mm Benelli Raffaello SA 12 Gauge")
    _185mm_benelli_supernova_12_gauge = EnumValue(158, "18.5mm Benelli Supernova 12 Gauge")
    _185mm_benelli_vinci_sa_12_gauge = EnumValue(159, "18.5mm Benelli Vinci SA 12 Gauge")
    _185mm_beretta_1201fp_sa_12_gauge = EnumValue(160, "18.5mm Beretta 1201FP SA 12 Gauge")
    _185mm_beretta_682_o_u_12_gauge = EnumValue(161, "18.5mm Beretta 682 O/U 12 Gauge")
    _156mm_beretta_682_o_u_20_gauge = EnumValue(162, "15.6mm Beretta 682 O/U 20 Gauge")
    _14mm_beretta_682_o_u_28_gauge = EnumValue(163, "14mm Beretta 682 O/U 28 Gauge")
    _104mm_beretta_682_o_u_410_bore = EnumValue(164, "10.4mm Beretta 682 O/U .410 Bore")
    _185mm_beretta_a303_sa_12_gauge = EnumValue(165, "18.5mm Beretta A303 SA 12 Gauge")
    _185mm_beretta_al391_sa_12_gauge = EnumValue(166, "18.5mm Beretta AL391 SA 12 Gauge")
    _156mm_beretta_al391_sa_20_gauge = EnumValue(167, "15.6mm Beretta AL391 SA 20 Gauge")
    _185mm_beretta_dt_10_o_u_12_gauge = EnumValue(168, "18.5mm Beretta DT-10 O/U 12 Gauge")
    beretta_silver_pigeon_o_u = EnumValue(169, "Beretta Silver Pigeon O/U")
    _185mm_beretta_xtrema_2_sa_12_gauge = EnumValue(170, "18.5mm Beretta Xtrema 2 SA 12 Gauge")
    _156mm_franchi_al_48_sa_20_gauge = EnumValue(171, "15.6mm Franchi AL-48 SA 20 Gauge")
    _14mm_franchi_al_48_sa_28_gauge = EnumValue(172, "14mm Franchi AL-48 SA 28 Gauge")
    _104mm_franchi_mod_410_fa_410_bore = EnumValue(173, "10.4mm Franchi mod .410 FA .410 Bore")
    _185mm_franchi_spas_12_sa_12_gauge = EnumValue(174, "18.5mm Franchi SPAS-12 SA 12 Gauge")
    _185mm_franchi_spas_15_sa_12_gauge = EnumValue(175, "18.5mm Franchi SPAS-15 SA 12 Gauge")
    _185mm_valtro_pm_5_pm_5_350_12_gauge = EnumValue(176, "18.5mm Valtro PM-5/PM-5-350 12 Gauge")
    blazer_f3_o_u = EnumValue(180, "Blazer F3 O/U")
    _185mm_hk_fabarm_fp6_12_gauge = EnumValue(181, "18.5mm HK FABARM FP6 12 Gauge")
    _185mm_hk_caws_fa_12_gauge = EnumValue(182, "18.5mm HK CAWS FA 12 Gauge")
    _185mm_baikal_mp_153_sa_12_gauge = EnumValue(200, "18.5mm Baikal MP-153 SA 12 Gauge")
    _185mm_bandayevsky_rb_12_12_gauge = EnumValue(201, "18.5mm Bandayevsky RB-12 12 Gauge")
    _185mm_molot_bekas_m_12_gauge = EnumValue(202, "18.5mm Molot Bekas-M 12 Gauge")
    _168mm_molot_bekas_m_16_gauge = EnumValue(203, "16.8mm Molot Bekas-M 16 Gauge")
    _185mm_toz_194_12_gauge = EnumValue(204, "18.5mm TOZ-194 12 Gauge")
    _23mm_ks_23 = EnumValue(205, "23mm KS-23")
    mts_255_revoler_12_gauge = EnumValue(206, "MTs-255 Revoler 12 Gauge")
    _185mm_rmb_93_12_gauge = EnumValue(207, "18.5mm RMB-93 12 Gauge")
    _185mm_saiga_12_sa_12_gauge = EnumValue(208, "18.5mm Saiga-12 SA 12 Gauge")
    _156mm_saiga_12_sa_20_gauge = EnumValue(209, "15.6mm Saiga-12 SA 20 Gauge")
    _104mm_saiga_12_sa_410_bore = EnumValue(210, "10.4mm Saiga-12 SA .410 Bore")
    _185mm_vepr_12_sa_12_gauge = EnumValue(211, "18.5mm Vepr-12 SA 12 Gauge")
    _185mm_fort_500_12_gauge = EnumValue(212, "18.5mm Fort 500 12 Gauge")
    _185mm_norinco_hp9_1_12_gauge = EnumValue(220, "18.5mm Norinco HP9-1 12 Gauge")
    default = other

    def get_marshaled_size(self):
        return 8
