'''
/*
 * Copyright (c) 2008-2022, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
 // header autogenerated using string template dis7javalicense.txt
'''

from .minefield_paint_scheme_algae import MinefieldPaintSchemeAlgae
from .minefield_paint_scheme_paint_scheme import MinefieldPaintSchemePaintScheme

import ctypes

UInt8 = ctypes.c_uint8
UInt16 = ctypes.c_uint16
UInt32 = ctypes.c_uint32

UByte = ctypes.c_ubyte
UInt  = ctypes.c_uint

# autogenerated using string template disbitset1.txt
# package edu.nps.moves.dis7.enumerations;

"""
/**
  * Generated from XML,
  *  UID 202, marshal size 8,
  * MinefieldDataPaintScheme
  */

"""

class MinefieldDataPaintSchemeBitField(ctypes.Structure):
    _fields_ = [
        # (bit position 0, length=2) Identifies the algae build-up on the mine,  use {@link MinefieldPaintSchemeAlgae} values for this field
        ("_algae", UByte, 2),

        # (bit position 2, length=6) Identifies the paint scheme of the mine,  use {@link MinefieldPaintSchemePaintScheme} values for this field
        ("_paintScheme", UByte, 6)
    ]

class MinefieldDataPaintScheme(ctypes.Union):
    _fields_ = [
        ("capabilities", MinefieldDataPaintSchemeBitField),
        ("asbyte", UInt8)
    ]

    def set_algae(self, value : MinefieldPaintSchemeAlgae):
        self.capabilities._algae = int(value)
    def get_algae(self) -> MinefieldPaintSchemeAlgae:
        return MinefieldPaintSchemeAlgae.get_enum(self._algae)
    Algae = property(get_algae, set_algae)

    def set_paintScheme(self, value : MinefieldPaintSchemePaintScheme):
        self.capabilities._paintScheme = int(value)
    def get_paintScheme(self) -> MinefieldPaintSchemePaintScheme:
        return MinefieldPaintSchemePaintScheme.get_enum(self._paintScheme)
    PaintScheme = property(get_paintScheme, set_paintScheme)


    def to_string(self):
        outputStream = ""
        outputStream += format(self.asbyte, '#032b') + "\n"
        outputStream += "Algae : " +  self.Algae.get_description + "\n"
        outputStream += "PaintScheme : " +  self.PaintScheme.get_description + "\n"
        return outputStream

    def __str__(self):
        return self.to_string()

    def __eq__(self, other):
        if isinstance(other, self.__class__):
            return self.__dict__ == other.__dict__
        else:
            return False

    def __ne__(self, other):
        return not self.__eq__(other)

    def diff(self,other) -> set:
        diffs = set()
        for key, value in self.__dict__.items():
            value2 = other.__dict__[key]
            if (value != value2):
                if type(value) is list:
                    diffs.add((key, str(value)))
                    diffs.add((key, str(value2)))
                elif (type(value).__module__ == "builtins"):
                    diffs.add((key, value))
                    diffs.add((key, value2))
                elif (isinstance(value, object)):
                    diffs.update(value.diff(value2))
                else:
                    diffs.add((key, value))
                    diffs.add((key, value2))
        return(diffs)

    def get_marshaled_size(self):
        return 8 
