'''
/*
 * Copyright (c) 2008-2022, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
 // header autogenerated using string template dis7javalicense.txt
'''


from enum import Enum, EnumMeta
from pprint import pprint, pformat
from collections import OrderedDict, namedtuple
import ctypes

UInt8 = ctypes.c_uint8
UInt16 = ctypes.c_uint16
UInt32 = ctypes.c_uint32

EnumValue = namedtuple('EnumValue', ['value', 'description'])

# autogenerated using string template disenumpart1.txt
#  package edu.nps.moves.dis7.enumerations;

'''
/**
  * This <code>enum</code> type is generated from XML,
  * SisoDate : 
  * UID 12,
  * marshal size 8;
  * PlatformSubsurfaceCategory has 20 enumerations total.
  */
'''

class EnumMeta(EnumMeta):
    def __getitem__(cls, name):
        try:
            return super().__getitem__(name)
        except KeyError as error:
            return cls.UNKNOWN
    
    def __getattr__(cls, name):
        try:
            return super().__getattr__(name)
        except AttributeError as error:
            return cls.UNKNOWN

class ExtensibleEnum(Enum):
    @classmethod
    def add_custom_value(cls, value: int, name: str, desc:str):
        existingItem = [item for item in cls._value2member_map_ if item.value == value]

        enumValue = EnumValue(value, desc)
        obj = object.__new__(cls)
        
        obj._value_ = enumValue
        obj._name_ = name      
        obj._desc = desc
        obj.__objclass__ = cls
        
        if not existingItem:
            cls._member_map_[name] = obj
            cls._value2member_map_[enumValue] = enumValue
            cls._member_names_.append(name)
        else:
            enumIndex = list(OrderedDict(cls.__members__).keys())[value]
            cls._member_map_[enumIndex] = obj

    @property
    def get_description(self):
        return self.value.description

    @classmethod
    def to_string(cls) -> str:
        return pformat(OrderedDict(cls.__members__))

    @classmethod
    def is_valid(cls, kind: Enum) -> bool:
        if kind is cls.UNKNOWN:
            return False
        return kind in iter(cls)

    @staticmethod
    def describe(self):
        return self.name, self.value

    @classmethod
    def value_list(cls):
        return list(map(lambda c: c.value, cls))

    @classmethod
    def _missing_(cls, value):
        return cls.default

    @classmethod
    def get_enum_key(cls, value:int) -> str:
        for unique_key, unique_value in OrderedDict(cls.__members__).items():
            if value == unique_value.value.value:
                return unique_key
        return 'UNKNOWN'

    @classmethod
    def get_enum(cls, value:int) -> Enum:
        key = cls.get_enum_key(value)
        return getattr(cls, key)

    def __int__(self):
        return self.value.value
    def diff(self,other) -> set:
        diffs = set()
        for key, value in self.__dict__.items():
            value2 = other.__dict__[key]
            if (value != value2):
                if type(value) is list:
                    diffs.add((key, str(value)))
                    diffs.add((key, str(value2)))
                elif (type(value).__module__ == "builtins"):
                    diffs.add((key, value))
                    diffs.add((key, value2))
                elif (isinstance(value, Enum)):
                    diffs.add((key, value))
                    diffs.add((key, value2))
                elif (isinstance(value, object)):
                    diffs.update(value.diff(value2))
                else:
                    diffs.add((key, value))
                    diffs.add((key, value2))
        return(diffs)

class PlatformSubsurfaceCategory(ExtensibleEnum, metaclass=EnumMeta):
    UNKNOWN = EnumValue(-1, "UNKNOWN Enum")
    other = EnumValue(0, "Other")
    ssbn_nuclear_ballistic_missile = EnumValue(1, "SSBN (Nuclear Ballistic Missile)")
    ssgn_nuclear_guided_missile = EnumValue(2, "SSGN (Nuclear Guided Missile)")
    ssn_nuclear_attack_torpedo = EnumValue(3, "SSN (Nuclear Attack - Torpedo)")
    ssg_conventional_guided_missile = EnumValue(4, "SSG (Conventional Guided Missile)")
    ss_conventional_attack_torpedo_patrol = EnumValue(5, "SS (Conventional Attack - Torpedo, Patrol)")
    ssan_nuclear_auxiliary = EnumValue(6, "SSAN (Nuclear Auxiliary)")
    ssa_conventional_auxiliary = EnumValue(7, "SSA (Conventional Auxiliary)")
    unmanned_underwater_vehicle_uuv = EnumValue(8, "Unmanned Underwater Vehicle (UUV)")
    ssb_submarine_ballistic_ballistic_missile_submarine = EnumValue(9, "SSB (Submarine Ballistic, Ballistic Missile Submarine)")
    ssc_coastal_submarine_over_150_tons = EnumValue(10, "SSC (Coastal Submarine, over 150 tons)")
    ssp_attack_submarine_diesel_air_independent_propulsion = EnumValue(11, "SSP (Attack Submarine - Diesel Air-Independent Propulsion)")
    ssm_midget_submarine_under_150_tons = EnumValue(12, "SSM (Midget Submarine, under 150 tons)")
    ssnr_special_attack_submarine = EnumValue(13, "SSNR (Special Attack Submarine)")
    sst_training_submarine = EnumValue(14, "SST (Training Submarine)")
    agss_auxiliary_submarine = EnumValue(15, "AGSS (Auxiliary Submarine)")
    semi_submersible_boats = EnumValue(16, "Semi-Submersible Boats")
    civilian_submarines = EnumValue(80, "Civilian Submarines")
    civilian_submersibles = EnumValue(81, "Civilian Submersibles")
    civilian_semi_submersible_boats = EnumValue(82, "Civilian Semi-Submersible Boats")
    default = other

    def get_marshaled_size(self):
        return 8
