'''
/*
 * Copyright (c) 2008-2022, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
 // header autogenerated using string template dis7javalicense.txt
'''

from .appearance_object_specific_chemical_type import AppearanceObjectSpecificChemicalType

import ctypes

UInt8 = ctypes.c_uint8
UInt16 = ctypes.c_uint16
UInt32 = ctypes.c_uint32

UByte = ctypes.c_ubyte
UInt  = ctypes.c_uint

# autogenerated using string template disbitset1.txt
# package edu.nps.moves.dis7.enumerations;

"""
/**
  * Generated from XML,
  *  UID 232, marshal size 16,
  * PointObjectAppearanceAirGroundBurst
  */

"""

class PointObjectAppearanceAirGroundBurstBitField(ctypes.Structure):
    _fields_ = [
        # (bit position 0, length=8) 8-bit unsigned integer indicating the percent opacity of the smoke (0..100),  use {@link UInt8} values for this field
        ("_opacityPercent", UByte, 8),

        # (bit position 8, length=8) 8-bit unsigned integer indicating the radius in meters of the cylinder which approximates an individual burst,  use {@link UInt8} values for this field
        ("_size", UByte, 8),

        # (bit position 16, length=8) 8-bit unsigned integer indicating the height in meters of the cylinder which approximates an individual burst,  use {@link UInt8} values for this field
        ("_height", UByte, 8),

        # (bit position 24, length=6) 6-bit unsigned integer indicating the number of bursts in the instance of tactical smoke,  use {@link UInt8} values for this field
        ("_numberofBursts", UByte, 6),

        # (bit position 30, length=2) Describes the chemical content of the smoke,  use {@link AppearanceObjectSpecificChemicalType} values for this field
        ("_chemicalType", UByte, 2)
    ]

class PointObjectAppearanceAirGroundBurst(ctypes.Union):
    _fields_ = [
        ("capabilities", PointObjectAppearanceAirGroundBurstBitField),
        ("asbyte", UInt8)
    ]

    def set_opacityPercent(self, value : UInt8):
        self.capabilities._opacityPercent = int(value)
    def get_opacityPercent(self) -> UInt8:
        return self.capabilities._opacityPercent
    OpacityPercent = property(get_opacityPercent, set_opacityPercent)

    def set_size(self, value : UInt8):
        self.capabilities._size = int(value)
    def get_size(self) -> UInt8:
        return self.capabilities._size
    Size = property(get_size, set_size)

    def set_height(self, value : UInt8):
        self.capabilities._height = int(value)
    def get_height(self) -> UInt8:
        return self.capabilities._height
    Height = property(get_height, set_height)

    def set_numberofBursts(self, value : UInt8):
        self.capabilities._numberofBursts = int(value)
    def get_numberofBursts(self) -> UInt8:
        return self.capabilities._numberofBursts
    NumberofBursts = property(get_numberofBursts, set_numberofBursts)

    def set_chemicalType(self, value : AppearanceObjectSpecificChemicalType):
        self.capabilities._chemicalType = int(value)
    def get_chemicalType(self) -> AppearanceObjectSpecificChemicalType:
        return AppearanceObjectSpecificChemicalType.get_enum(self._chemicalType)
    ChemicalType = property(get_chemicalType, set_chemicalType)


    def to_string(self):
        outputStream = ""
        outputStream += format(self.asbyte, '#032b') + "\n"
        outputStream += "OpacityPercent : " +  str(self.OpacityPercent) + "\n"
        outputStream += "Size : " +  str(self.Size) + "\n"
        outputStream += "Height : " +  str(self.Height) + "\n"
        outputStream += "NumberofBursts : " +  str(self.NumberofBursts) + "\n"
        outputStream += "ChemicalType : " +  self.ChemicalType.get_description + "\n"
        return outputStream

    def __str__(self):
        return self.to_string()

    def __eq__(self, other):
        if isinstance(other, self.__class__):
            return self.__dict__ == other.__dict__
        else:
            return False

    def __ne__(self, other):
        return not self.__eq__(other)

    def diff(self,other) -> set:
        diffs = set()
        for key, value in self.__dict__.items():
            value2 = other.__dict__[key]
            if (value != value2):
                if type(value) is list:
                    diffs.add((key, str(value)))
                    diffs.add((key, str(value2)))
                elif (type(value).__module__ == "builtins"):
                    diffs.add((key, value))
                    diffs.add((key, value2))
                elif (isinstance(value, object)):
                    diffs.update(value.diff(value2))
                else:
                    diffs.add((key, value))
                    diffs.add((key, value2))
        return(diffs)

    def get_marshaled_size(self):
        return 16 
