'''
/*
 * Copyright (c) 2008-2022, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
 // header autogenerated using string template dis7javalicense.txt
'''

from .color import Color
from .building_paint_scheme import BuildingPaintScheme

import ctypes

UInt8 = ctypes.c_uint8
UInt16 = ctypes.c_uint16
UInt32 = ctypes.c_uint32

UByte = ctypes.c_ubyte
UInt  = ctypes.c_uint

# autogenerated using string template disbitset1.txt
# package edu.nps.moves.dis7.enumerations;

"""
/**
  * Generated from XML,
  *  UID 230, marshal size 16,
  * PointObjectAppearanceBuildingStructure
  */

"""

class PointObjectAppearanceBuildingStructureBitField(ctypes.Structure):
    _fields_ = [
        # (bit position 0, length=8) Describes the color of the building or structure,  use {@link Color} values for this field
        ("_color", UByte, 8),

        # (bit position 8, length=8) Describes the visual paint design,  use {@link BuildingPaintScheme} values for this field
        ("_paintScheme", UByte, 8),

        # (bit position 16, boolean) Describes whether the aperture (e.g., tent) is open or closed,  use {@link UInt8} values for this field
        ("_isApertureOpen", UByte, 1)
    ]

class PointObjectAppearanceBuildingStructure(ctypes.Union):
    _fields_ = [
        ("capabilities", PointObjectAppearanceBuildingStructureBitField),
        ("asbyte", UInt8)
    ]

    def set_color(self, value : Color):
        self.capabilities._color = int(value)
    def get_color(self) -> Color:
        return Color.get_enum(self._color)
    Color = property(get_color, set_color)

    def set_paintScheme(self, value : BuildingPaintScheme):
        self.capabilities._paintScheme = int(value)
    def get_paintScheme(self) -> BuildingPaintScheme:
        return BuildingPaintScheme.get_enum(self._paintScheme)
    PaintScheme = property(get_paintScheme, set_paintScheme)

    def set_isApertureOpen(self, value : UInt8):
        self.capabilities._isApertureOpen = int(value)
    def get_isApertureOpen(self) -> UInt8:
        return self.capabilities._isApertureOpen
    IsApertureOpen = property(get_isApertureOpen, set_isApertureOpen)


    def to_string(self):
        outputStream = ""
        outputStream += format(self.asbyte, '#032b') + "\n"
        outputStream += "Color : " +  self.Color.get_description + "\n"
        outputStream += "PaintScheme : " +  self.PaintScheme.get_description + "\n"
        outputStream += "IsApertureOpen : " +  str(self.IsApertureOpen) + "\n"
        return outputStream

    def __str__(self):
        return self.to_string()

    def __eq__(self, other):
        if isinstance(other, self.__class__):
            return self.__dict__ == other.__dict__
        else:
            return False

    def __ne__(self, other):
        return not self.__eq__(other)

    def diff(self,other) -> set:
        diffs = set()
        for key, value in self.__dict__.items():
            value2 = other.__dict__[key]
            if (value != value2):
                if type(value) is list:
                    diffs.add((key, str(value)))
                    diffs.add((key, str(value2)))
                elif (type(value).__module__ == "builtins"):
                    diffs.add((key, value))
                    diffs.add((key, value2))
                elif (isinstance(value, object)):
                    diffs.update(value.diff(value2))
                else:
                    diffs.add((key, value))
                    diffs.add((key, value2))
        return(diffs)

    def get_marshaled_size(self):
        return 16 
