'''
/*
 * Copyright (c) 2008-2022, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
 // header autogenerated using string template dis7javalicense.txt
'''


from enum import Enum, EnumMeta
from pprint import pprint, pformat
from collections import OrderedDict, namedtuple
import ctypes

UInt8 = ctypes.c_uint8
UInt16 = ctypes.c_uint16
UInt32 = ctypes.c_uint32

EnumValue = namedtuple('EnumValue', ['value', 'description'])

# autogenerated using string template disenumpart1withfootnote.txt
# package edu.nps.moves.dis7.enumerations;

'''
/**
  *  UID 132, marshal size 8;
  * SpecificDimensionEnumerationsforAirAreaSize has 6 enumerations total.
  * The gaps in enumeration values are intentional and are reserved for future additions.
  * @see <a href="https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html">Java Tutorials: Enum Types</a>
  * @see java.lang.Enum
  */
'''

class EnumMeta(EnumMeta):
    def __getitem__(cls, name):
        try:
            return super().__getitem__(name)
        except KeyError as error:
            return cls.UNKNOWN
    
    def __getattr__(cls, name):
        try:
            return super().__getattr__(name)
        except AttributeError as error:
            return cls.UNKNOWN

class ExtensibleEnum(Enum):
    @classmethod
    def add_custom_value(cls, value: int, name: str, desc:str):
        existingItem = [item for item in cls._value2member_map_ if item.value == value]

        enumValue = EnumValue(value, desc)
        obj = object.__new__(cls)
        
        obj._value_ = enumValue
        obj._name_ = name      
        obj._desc = desc
        obj.__objclass__ = cls
        
        if not existingItem:
            cls._member_map_[name] = obj
            cls._value2member_map_[enumValue] = enumValue
            cls._member_names_.append(name)
        else:
            enumIndex = list(OrderedDict(cls.__members__).keys())[value]
            cls._member_map_[enumIndex] = obj

    @property
    def get_description(self):
        return self.value.description

    @classmethod
    def to_string(cls) -> str:
        return pformat(OrderedDict(cls.__members__))

    @classmethod
    def is_valid(cls, kind: Enum) -> bool:
        if kind is cls.UNKNOWN:
            return False
        return kind in iter(cls)

    @staticmethod
    def describe(self):
        return self.name, self.value

    @classmethod
    def value_list(cls):
        return list(map(lambda c: c.value, cls))

    @classmethod
    def _missing_(cls, value):
        return cls.default

    @classmethod
    def get_enum_key(cls, value:int) -> str:
        for unique_key, unique_value in OrderedDict(cls.__members__).items():
            if value == unique_value.value.value:
                return unique_key
        return 'UNKNOWN'

    @classmethod
    def get_enum(cls, value:int) -> Enum:
        key = cls.get_enum_key(value)
        return getattr(cls, key)

    def __int__(self):
        return self.value.value

class SpecificDimensionEnumerationsforAirAreaSize(ExtensibleEnum, metaclass=EnumMeta):
    UNKNOWN = EnumValue(-1, "UNKNOWN Enum")
    small_flock_swarm_5km_long_x_5m_wide_1km_x_5m = EnumValue(222, "Small Flock/Swarm (.5km long x 5m wide - 1km x 5m)")
    small_flock_swarm_dense_5km_long_x_5m_wide_1km_x_5m = EnumValue(223, "Small Flock/Swarm, Dense (.5km long x 5m wide - 1km x 5m)")
    medium_flock_swarm_1km_long_x_10m_wide_2km_x_10m = EnumValue(224, "Medium Flock/Swarm (1km long x 10m wide - 2km x 10m)")
    medium_flock_swarm_dense_1km_long_x_10m_wide_2km_x_10m = EnumValue(225, "Medium Flock/Swarm, Dense (1km long x 10m wide - 2km x 10m)")
    large_flock_swarm_10km_long_x_100m_wide_20km_x_100m = EnumValue(226, "Large Flock/Swarm (10km long x 100m wide - 20km x 100m)")
    large_flock_swarm_dense_10km_long_x_100m_wide_20km_x_100m = EnumValue(227, "Large Flock/Swarm, Dense (10km long x 100m wide - 20km x 100m)")
    default = small_flock_swarm_5km_long_x_5m_wide_1km_x_5m

    def get_marshaled_size(self):
        return 8
