"""management.py
20 Entity Management
"""
import enum


"""20.1 Aggregates"""

# [UID 204]
class AggregateState(enum.IntEnum):
    """20.1.1 Aggregate State [UID 204]"""
    OTHER = 0
    AGGREGATED = 1
    DISAGGREGATED = 2
    FULLY_DISAGGREGATED = 3
    PSEUDO_DISAGGREGATED = 4
    PARTIALLY_DISAGGREGATED = 5


# [UID 205]
class Formation(enum.IntEnum):
    """20.1.2 Formation [UID 205]"""
    OTHER = 0
    ASSEMBLY = 1
    VEE = 2
    WEDGE = 3
    LINE = 4
    COLUMN = 5


"""20.1.3 Aggregate Type"""

# [UID 206]
class AggregateKind(enum.IntEnum):
    """20.1.3.1 Aggregate Kind [UID 206]"""
    OTHER = 0
    MILITARY_HIERARCHY = 1
    COMMON_TYPE = 2
    COMMON_MISSION = 3
    SIMILAR_CAPABILITIES = 4
    COMMON_LOCATION = 5


"""20.3 IsPartOf"""

# [UID 210]
class Nature(enum.IntEnum):
    """20.3.1 Nature [UID 210]"""
    OTHER = 0
    HOST_FIREABLE_MUNITION = 1
    MUNITION_CARRIED_AS_CARGO = 2
    FUEL_CARRIED_AS_CARGO = 3
    GUNMOUNT_ATTACHED_TO_HOST = 4
    COMPUTER_GENERATED_FORCES_CARRIED_AS_CARGO = 5
    VEHICLE_CARRIED_AS_CARGO = 6
    EMITTER_MOUNTED_ON_HOST = 7
    MOVABLE_COMMAND_AND_CONTROL_ENTITY_CARRIED_ABOARD_HOST = 8
    ENTITY_STATIONED_AT_POSITION_WITH_RESPECT_TO_HOST = 9
    TEAM_MEMBER_IN_FORMATION_WITH = 10


# [UID 211]
class Position(enum.IntEnum):
    """20.3.2 Position [UID 211]"""
    OTHER = 0
    ON_TOP_OF = 1
    INSIDE_OF = 2


# [UID 212]
class StationName(enum.IntEnum):
    """20.3.3 Station Name [UID 212]"""
    OTHER = 0
    AIRCRAFT_WINGSTATION = 1
    SHIP_FORWARD_GUNMOUNT_STARBOARD = 2
    SHIP_FORWARD_GUNMOUNT_PORT = 3
    SHIP_FORWARD_GUNMOUNT_CENTERLINE = 4
    SHIP_AFT_GUNMOUNT_STARBOARD = 5
    SHIP_AFT_GUNMOUNT_PORT = 6
    SHIP_AFT_GUNMOUNT_CENTERLINE = 7
    FORWARD_TORPEDO_TUBE = 8
    AFT_TORPEDO_TUBE = 9
    BOMB_BAY = 10
    CARGO_BAY = 11
    TRUCK_BED = 12
    TRAILER_BED = 13
    WELL_DECK = 14
    ON_STATION_RANGE_AND_BEARING = 15
    ON_STATION_XYZ = 16
    AIR_TO_AIR_REFUELING_BOOM = 17
    AERIAL_REFUELING_RECEPTACLE = 18
    PORT_SIDE_REFUELING_DROGUE = 19
    STARBOARD_SIDE_REFUELING_DROGUE = 20
    CENTER_REFUELING_DROGUE = 21
    AIR_REFUELING_PROBE = 22


"""20.4 IsGroupOf"""

# [UID 213]
class GroupedEntityCategory(enum.IntEnum):
    """20.4.1 Grouped Entity Category [UID 213]"""
    UNDEFINED = 0
    BASIC_GROUND_COMBAT_VEHICLE = 1
    ENHANCED_GROUND_COMBAT_VEHICLE = 2
    BASIC_GROUND_COMBAT_SOLDIER = 3
    ENHANCED_GROUND_COMBAT_SOLDIER = 4
    BASIC_ROTOR_WING_AIRCRAFT = 5
    ENHANCED_ROTOR_WING_AIRCRAFT = 6
    BASIC_FIXED_WING_AIRCRAFT = 7
    ENHANCED_FIXED_WING_AIRCRAFT = 8
    GROUND_LOGISTICS_VEHICLE = 9


# [UID 214]
class RestStatus(enum.IntEnum):
    """20.4.2 Rest Status [UID 214]"""
    NOT_RESTED = 0  # Has not slept in the last three days
    SLEPT_1_HOUR_PER_DAY = 1
    SLEPT_2_HOURS_PER_DAY = 2
    SLEPT_3_HOURS_PER_DAY = 3
    SLEPT_4_HOURS_PER_DAY = 4
    SLEPT_5_HOURS_PER_DAY = 5
    SLEPT_6_HOURS_PER_DAY = 6
    SLEPT_7_HOURS_PER_DAY = 7
    FULLY_RESTED = 8  # Has slept an average of 8 hours per day in the last three days


"""20.5 Transfer Ownership"""

# [UID 224]
class TransferType(enum.IntEnum):
    """20.5.1 Transfer Type [UID 224]"""
    OTHER = 0
    PUSH_TRANSFER_ENTITY = 1
    AUTOMATIC_PULL_TRANSFER_ENTITY = 2
    NOT_USED1 = 3
    PUSH_TRANSFER_ENVIRONMENTAL_PROCESS = 4
    AUTOMATIC_PULL_TRANSFER_ENVIRONMENTAL_PROCESS = 5
    NOT_USED2 = 6
    CANCEL_TRANSFER = 7
    MANUAL_PULL_TRANSFER_ENTITY = 8
    MANUAL_PULL_TRANSFER_ENVIRONMENTAL_PROCESS = 9
    REMOVE_ENTITY = 10


# [UID 327]
class MunitionExpendableStatus(enum.IntEnum):
    """20.5.2 Munition/Expendable Status [UID 327]"""
    OTHER = 0
    READY = 1
    INVENTORY = 2

# [UID 328]
class FuelMeasurementUnit(enum.IntEnum):
    """20.5.3 Fuel Measurement Unit [UID 328]"""
    OTHER = 0
    LITER = 1
    KILOGRAM = 2


# [UID 329]
class FuelLocation(enum.IntEnum):
    """20.5.4 Fuel Location [UID 329]"""
    OTHER = 0

# [UID 330]
class AssociationType(enum.IntEnum):
    """20.5.5 Association Type [UID 330]"""
    OTHER = 0
    TARGET_ENTITY = 1
    TARGET_LOCATION = 2
    HOME_BASE_LOCATION = 3
    CAP_POINT_LOCATION = 4
    FLIGHT_LEADER = 5
    FLIGHT_MEMBER = 6
    IP_POINT = 7
    RENDEZVOUS_POINT = 8
    ON_STATION_LOCATION = 9
    LANDING_ZONE_LOCATION = 10
    DOWNED_PILOT = 11
    TANKER_ENTITY_CURRENTLY_REFUELING_THE_TRANSFERRED_ENTITY = 12
    TANKER_ENTITY_THE_TRANSFERRED_ENTITY_IS_HEADING_TO_REFUEL = 13
    ENTITY_HEADING_TO_JOIN_UP_WITH = 14


# [UID 331]
class SensorStatus(enum.IntEnum):
    """20.5.6 Sensor On/Off Status [UID 331]"""
    OFF = 0
    ON = 1


# [UID 332]
class OwnershipStatus(enum.IntEnum):
    """20.5.7 Ownership Status [UID 332]"""
    OTHER = 0
    NEW_OWNER = 1
    OWNERSHIP_QUERY_RESPONSE = 2
    OWNERSHIP_CONFLICT = 3
    LOCAL_ENTITY_CANCELLED_AUTO_RESOLVE_CONFLICT = 4
    LOCAL_ENTITY_CANCELLED_MANUAL_RESOLVE_CONFLICT = 5
    LOCAL_ENTITY_CANCELLED_REMOVE_ENTITY_TCR_RECEIVED = 6
