"""radio.py

5.8 Radio Kind
"""
import enum


# [UID 22]
class RadioCategory(enum.IntEnum):
    """5.8.3 Category [UID 22]"""
    OTHER = 0
    VOICE_TRANSMISSION_RECEPTION = 1
    DATA_LINK_TRANSMISSION_RECEPTION = 2
    VOICE_AND_DATA_LINK_TRANSMISSION_RECEPTION = 3
    ILS_GLIDESLOPE_TRANSMITTER = 4
    ILS_LOCALIZER_TRANSMITTER = 5
    ILS_OUTER_MARKER_BEACON = 6
    ILS_MIDDLE_MARKER_BEACON = 7
    ILS_INNER_MARKER_BEACON = 8
    ILS_RECEIVER = 9
    TACAN_TRANSMITTER = 10
    TACAN_RECEIVER = 11
    TACAN_TRANSMITTER_RECEIVER = 12
    VOR_TRANSMITTER = 13
    VOR_WITH_DME_TRANSMITTER = 14
    COMBINED_VOR_ILS_RECEIVER = 15
    VORTAC_TRANSMITTER = 16
    NDB_TRANSMITTER = 17
    NDB_RECEIVER = 18
    NDB_WITH_DME_TRANSMITTER = 19
    DISTANCE_MEASURING_EQUIPMENT_DME = 20
    LINK_16_TERMINAL = 21
    LINK_11_TERMINAL = 22
    LINK_11B_TERMINAL = 23
    EPLRS_SADL_TERMINAL = 24
    F_22_INTRA_FLIGHT_DATA_LINK_IFDL = 25
    F_35_MULTIFUNCTION_ADVANCED_DATA_LINK_MADL = 26
    SINCGARS_TERMINAL = 27
    L_BAND_SATCOM_TERMINAL = 28
    IBS_TERMINAL = 29
    GPS = 30
    TACTICAL_VIDEO = 31
    AIR_TO_AIR_MISSILE_DATALINK = 32
    LINK_16_SURROGATE_FOR_NON_NATO_TDL_TERMINAL = 33
    MQ_1_9_C_BAND_LOS_DATALINK = 34
    MQ_1_9_KU_BAND_SATCOM_DATALINK = 35
    AIR_TO_GROUND_WEAPON_DATALINK = 36
    AUTOMATIC_IDENTIFICATION_SYSTEM_AIS = 37
    JPALS_DATA_LINK = 38
    CSAR_RADIO = 40
    C_UAS_RADIO = 41
    EMERGENCY_POSITION_INDICATING_RADIO_BEACONS_EPIRB = 42
    ELECTRONIC_ATTACK_SYSTEMS = 50
    TACTICAL_TARGETING_NETWORK_TECHNOLOGY_TTNT = 51


# [UID 23]
class RadioSubcategory(enum.IntEnum):
    """5.8.4 Subcategory [UID 23]"""
    OTHER = 0
    JETDS_NONSPECIFIC_SERIES = 1
    MANUFACTURER_DESIGNATION = 2
    NATIONAL_DESIGNATION = 3
    JETDS_ARC_SET_1 = 11
    JETDS_ARC_SET_2 = 12
    JETDS_ARC_SET_3 = 13
    JETDS_ARC_SET_4 = 14
    JETDS_BRC_SET_1 = 15
    JETDS_BRC_SET_2 = 16
    JETDS_BRC_SET_3 = 17
    JETDS_BRC_SET_4 = 18
    JETDS_CRC_SET_1 = 19
    JETDS_CRC_SET_2 = 20
    JETDS_CRC_SET_3 = 21
    JETDS_CRC_SET_4 = 22
    JETDS_DRC_SET_1 = 23
    JETDS_DRC_SET_2 = 24
    JETDS_DRC_SET_3 = 25
    JETDS_DRC_SET_4 = 26
    JETDS_FRC_SET_1 = 27
    JETDS_FRC_SET_2 = 28
    JETDS_FRC_SET_3 = 29
    JETDS_FRC_SET_4 = 30
    JETDS_GRC_SET_1 = 31
    JETDS_GRC_SET_2 = 32
    JETDS_GRC_SET_3 = 33
    JETDS_GRC_SET_4 = 34
    JETDS_KRC_SET_1 = 35
    JETDS_KRC_SET_2 = 36
    JETDS_KRC_SET_3 = 37
    JETDS_KRC_SET_4 = 38
    JETDS_MRC_SET_1 = 39
    JETDS_MRC_SET_2 = 40
    JETDS_MRC_SET_3 = 41
    JETDS_MRC_SET_4 = 42
    JETDS_PRC_SET_1 = 43
    JETDS_PRC_SET_2 = 44
    JETDS_PRC_SET_3 = 45
    JETDS_PRC_SET_4 = 46
    JETDS_SRC_SET_1 = 47
    JETDS_SRC_SET_2 = 48
    JETDS_SRC_SET_3 = 49
    JETDS_SRC_SET_4 = 50
    JETDS_TRC_SET_1 = 51
    JETDS_TRC_SET_2 = 52
    JETDS_TRC_SET_3 = 53
    JETDS_TRC_SET_4 = 54
    JETDS_VRC_SET_1 = 55
    JETDS_VRC_SET_2 = 56
    JETDS_VRC_SET_3 = 57
    JETDS_VRC_SET_4 = 58
    JETDS_WRC_SET_1 = 59
    JETDS_WRC_SET_2 = 60
    JETDS_WRC_SET_3 = 61
    JETDS_WRC_SET_4 = 62
    JETDS_ZRC_SET_1 = 63
    JETDS_ZRC_SET_2 = 64
    JETDS_ZRC_SET_3 = 65
    JETDS_ZRC_SET_4 = 66
   